baseurl = "https://example.com/"  # Include trailing slash
title = "Space of Happiness"
theme = "newsroom"
DefaultContentLanguage = "ru"
languageCode = "ru"
author = "Space of Happiness"
designer = ""
copyright = "Copyright Â© 2019, Space of Happiness; all rights reserved."
canonifyurls = true
paginate = 5
enableEmoji = true

# Enable syntax highlighting
# comment or delete the following lines 11 ~ 14
# pygmentsCodefences = true
# pygmentsCodefencesGuessSyntax = true
# pygmentsUseClasses=true
# pygmentsOptions = "linenos=table"

# If you want to use disqus, uncomment the line below
# disqusShortname = "yourdiscussshortname"

# ids used below are not valid. Replace with valid ones
[params]
  # ga_analytics = "" # google analytics ID e.g UA-116386578-1
  
  # ga_verify = "" # google verification code e.g 5jb-rxeBfITeJQKOuUss3ud6FPGTxXkCho-ZN5qlrZg
  # twitter = "" # twitter handle e.g @weru

[imaging]
resampleFilter = "Lanczos"
quality = 75
disableDate = true
disableLatLong = true